{{ config(schema='Inventory') }}

SELECT DISTINCT E.EMPLOYEE_KEY,P.PRODUCTKEY,V.VENDORKEY,OD."DATE" AS OrderDate,DS.ShipMethodKey,
DD."DATE" AS  DueDate ,SD."DATE"  AS ShipDate,DW.WareHouseKey,PH.PURCHASEORDERID AS PurchaseOrderNumber,
POD.PURCHASEORDERDETAILID PurchaseOrderLineNumber,PH.REVISIONNUMBER,POD.ORDERQTY,POD.UNITPRICE,
POD.RECEIVEDQTY,POD.REJECTEDQTY,AverageLeadTime,PH.SUBTOTAL ,PH.TAXAMT,PH.FREIGHT, COALESCE(PH.SUBTOTAL+PH.TAXAMT+PH.FREIGHT,0) TotalDue
FROM  {{ source('inventory','purchaseorderheader') }}  PH
JOIN {{ source('inventory','purchaseorderdetail') }}  POD ON (PH.PURCHASEORDERID=POD.PURCHASEORDERID)
JOIN {{ ref('DIMEMPLOYEE') }} E ON (PH.EMPLOYEEID=E.BUSINESSENTITYID)
JOIN {{ ref('DIMPRODUCT') }} P ON (P.PRODUCTID=POD.PRODUCTID)
JOIN {{ ref('DIMVENDOR') }} V ON (PH.VENDORID=V.BUSINESSENTITYID)
JOIN {{ ref('DIMSHIPMETHOD') }} DS ON (DS.SHIPMETHODID=PH.SHIPMETHODID)
JOIN {{ ref('DIM_DATE') }} OD ON (OD."DATE" =CAST( PH.ORDERDATE AS date))
JOIN {{ ref('DIM_DATE') }} SD ON (SD."DATE" =CAST(PH.SHIPDATE AS date))
JOIN {{ ref('DIM_DATE') }} DD ON (DD."DATE" =CAST(POD.DUEDATE AS date))
JOIN {{ source('inventory','storagelocation') }}  SL ON (SL.PRODUCTID=P.PRODUCTID)
JOIN {{ ref('DIMWAREHOUSE') }}  DW ON (DW.WAREHOUSEID=SL.LOCATIONID)
JOIN {{ source('inventory','productvendor') }} PV ON (PV.PRODUCTID=POD.PRODUCTID AND PV.BUSINESSENTITYID=V.BUSINESSENTITYID)
